//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Счет в ЦБ
 * 
 * <p>Java class for TAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TnewAccountRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountNumber" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *         &lt;element name="Status" type="{urn:dmt:custodian2016}TAccountStatus"/&gt;
 *         &lt;element name="State" type="{urn:dmt:custodian2016}TAccountState"/&gt;
 *         &lt;element name="accountDateopen" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="accountDateClose" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="accountDateactivated" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Restrictions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="row" type="{urn:dmt:custodian2016}TAccountRestriction"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CoOwners" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="CoOwner" type="{urn:dmt:custodian2016}TCustomer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Level" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="NDU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="NBU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NBU" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="deponent_id" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="BaseAggregated_id" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SFS" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="responseCode" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="status" type="{urn:dmt:custodian2016}TSFSstatus" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAccount", propOrder = {
    "accountNumber",
    "status",
    "state",
    "accountDateopen",
    "accountDateClose",
    "accountDateactivated",
    "restrictions",
    "coOwners",
    "level",
    "nbu",
    "accountID",
    "sfs"
})
@XmlSeeAlso({
    TAccountListV2RowFull.class
})
public class TAccount
    extends TnewAccountRequest
{

    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(name = "Status", required = true)
    protected BigInteger status;
    @XmlElement(name = "State", required = true)
    protected BigInteger state;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accountDateopen;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accountDateClose;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accountDateactivated;
    @XmlElement(name = "Restrictions")
    protected TAccount.Restrictions restrictions;
    @XmlElement(name = "CoOwners")
    protected TAccount.CoOwners coOwners;
    @XmlElement(name = "Level")
    protected TAccount.Level level;
    @XmlElement(name = "NBU")
    protected TAccount.NBU nbu;
    @XmlElement(name = "AccountID", required = true)
    protected BigInteger accountID;
    @XmlElement(name = "SFS")
    protected TAccount.SFS sfs;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setState(BigInteger value) {
        this.state = value;
    }

    /**
     * Gets the value of the accountDateopen property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccountDateopen() {
        return accountDateopen;
    }

    /**
     * Sets the value of the accountDateopen property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccountDateopen(XMLGregorianCalendar value) {
        this.accountDateopen = value;
    }

    /**
     * Gets the value of the accountDateClose property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccountDateClose() {
        return accountDateClose;
    }

    /**
     * Sets the value of the accountDateClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccountDateClose(XMLGregorianCalendar value) {
        this.accountDateClose = value;
    }

    /**
     * Gets the value of the accountDateactivated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccountDateactivated() {
        return accountDateactivated;
    }

    /**
     * Sets the value of the accountDateactivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccountDateactivated(XMLGregorianCalendar value) {
        this.accountDateactivated = value;
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link TAccount.Restrictions }
     *     
     */
    public TAccount.Restrictions getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccount.Restrictions }
     *     
     */
    public void setRestrictions(TAccount.Restrictions value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the coOwners property.
     * 
     * @return
     *     possible object is
     *     {@link TAccount.CoOwners }
     *     
     */
    public TAccount.CoOwners getCoOwners() {
        return coOwners;
    }

    /**
     * Sets the value of the coOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccount.CoOwners }
     *     
     */
    public void setCoOwners(TAccount.CoOwners value) {
        this.coOwners = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link TAccount.Level }
     *     
     */
    public TAccount.Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccount.Level }
     *     
     */
    public void setLevel(TAccount.Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the nbu property.
     * 
     * @return
     *     possible object is
     *     {@link TAccount.NBU }
     *     
     */
    public TAccount.NBU getNBU() {
        return nbu;
    }

    /**
     * Sets the value of the nbu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccount.NBU }
     *     
     */
    public void setNBU(TAccount.NBU value) {
        this.nbu = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountID(BigInteger value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the sfs property.
     * 
     * @return
     *     possible object is
     *     {@link TAccount.SFS }
     *     
     */
    public TAccount.SFS getSFS() {
        return sfs;
    }

    /**
     * Sets the value of the sfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccount.SFS }
     *     
     */
    public void setSFS(TAccount.SFS value) {
        this.sfs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="CoOwner" type="{urn:dmt:custodian2016}TCustomer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "coOwner"
    })
    public static class CoOwners {

        @XmlElement(name = "CoOwner")
        protected List<TCustomer> coOwner;

        /**
         * Gets the value of the coOwner property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the coOwner property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCoOwner().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TCustomer }
         * 
         * 
         */
        public List<TCustomer> getCoOwner() {
            if (coOwner == null) {
                coOwner = new ArrayList<TCustomer>();
            }
            return this.coOwner;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NDU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="NBU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ndu",
        "nbu"
    })
    public static class Level {

        @XmlElement(name = "NDU", required = true)
        protected Object ndu;
        @XmlElement(name = "NBU", required = true)
        protected Object nbu;

        /**
         * Gets the value of the ndu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNDU() {
            return ndu;
        }

        /**
         * Sets the value of the ndu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNDU(Object value) {
            this.ndu = value;
        }

        /**
         * Gets the value of the nbu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNBU() {
            return nbu;
        }

        /**
         * Sets the value of the nbu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNBU(Object value) {
            this.nbu = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="deponent_id" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="BaseAggregated_id" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deponentId",
        "baseAggregatedId"
    })
    public static class NBU {

        @XmlElement(name = "deponent_id")
        protected Object deponentId;
        @XmlElement(name = "BaseAggregated_id")
        protected String baseAggregatedId;

        /**
         * Gets the value of the deponentId property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeponentId() {
            return deponentId;
        }

        /**
         * Sets the value of the deponentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeponentId(Object value) {
            this.deponentId = value;
        }

        /**
         * Gets the value of the baseAggregatedId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseAggregatedId() {
            return baseAggregatedId;
        }

        /**
         * Sets the value of the baseAggregatedId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseAggregatedId(String value) {
            this.baseAggregatedId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="row" type="{urn:dmt:custodian2016}TAccountRestriction"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class Restrictions {

        @XmlElement(required = true)
        protected List<TAccountRestriction> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TAccountRestriction }
         * 
         * 
         */
        public List<TAccountRestriction> getRow() {
            if (row == null) {
                row = new ArrayList<TAccountRestriction>();
            }
            return this.row;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="responseCode" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="status" type="{urn:dmt:custodian2016}TSFSstatus" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "state",
        "responseCode",
        "status"
    })
    public static class SFS {

        protected boolean state;
        protected String responseCode;
        protected BigInteger status;

        /**
         * Gets the value of the state property.
         * 
         */
        public boolean isState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         */
        public void setState(boolean value) {
            this.state = value;
        }

        /**
         * Gets the value of the responseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseCode() {
            return responseCode;
        }

        /**
         * Sets the value of the responseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseCode(String value) {
            this.responseCode = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStatus(BigInteger value) {
            this.status = value;
        }

    }

}
