//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.30 at 03:15:09 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAccountRestrictionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAccountRestrictionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Name"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="400"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Limitations"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Receive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Send" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Voting" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Change" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Benefit" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="isBlocking" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAccountRestrictionType", propOrder = {
    "id",
    "name",
    "limitations"
})
public class TAccountRestrictionType {

    protected int id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Limitations", required = true)
    protected TAccountRestrictionType.Limitations limitations;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the limitations property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountRestrictionType.Limitations }
     *     
     */
    public TAccountRestrictionType.Limitations getLimitations() {
        return limitations;
    }

    /**
     * Sets the value of the limitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountRestrictionType.Limitations }
     *     
     */
    public void setLimitations(TAccountRestrictionType.Limitations value) {
        this.limitations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Receive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Send" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Voting" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Change" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Benefit" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="isBlocking" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "receive",
        "send",
        "voting",
        "change",
        "benefit",
        "other",
        "isBlocking"
    })
    public static class Limitations {

        @XmlElement(name = "Receive")
        protected boolean receive;
        @XmlElement(name = "Send")
        protected boolean send;
        @XmlElement(name = "Voting")
        protected boolean voting;
        @XmlElement(name = "Change")
        protected boolean change;
        @XmlElement(name = "Benefit")
        protected boolean benefit;
        @XmlElement(name = "Other")
        protected boolean other;
        protected boolean isBlocking;

        /**
         * Gets the value of the receive property.
         * 
         */
        public boolean isReceive() {
            return receive;
        }

        /**
         * Sets the value of the receive property.
         * 
         */
        public void setReceive(boolean value) {
            this.receive = value;
        }

        /**
         * Gets the value of the send property.
         * 
         */
        public boolean isSend() {
            return send;
        }

        /**
         * Sets the value of the send property.
         * 
         */
        public void setSend(boolean value) {
            this.send = value;
        }

        /**
         * Gets the value of the voting property.
         * 
         */
        public boolean isVoting() {
            return voting;
        }

        /**
         * Sets the value of the voting property.
         * 
         */
        public void setVoting(boolean value) {
            this.voting = value;
        }

        /**
         * Gets the value of the change property.
         * 
         */
        public boolean isChange() {
            return change;
        }

        /**
         * Sets the value of the change property.
         * 
         */
        public void setChange(boolean value) {
            this.change = value;
        }

        /**
         * Gets the value of the benefit property.
         * 
         */
        public boolean isBenefit() {
            return benefit;
        }

        /**
         * Sets the value of the benefit property.
         * 
         */
        public void setBenefit(boolean value) {
            this.benefit = value;
        }

        /**
         * Gets the value of the other property.
         * 
         */
        public boolean isOther() {
            return other;
        }

        /**
         * Sets the value of the other property.
         * 
         */
        public void setOther(boolean value) {
            this.other = value;
        }

        /**
         * Gets the value of the isBlocking property.
         * 
         */
        public boolean isIsBlocking() {
            return isBlocking;
        }

        /**
         * Sets the value of the isBlocking property.
         * 
         */
        public void setIsBlocking(boolean value) {
            this.isBlocking = value;
        }

    }

}
