//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TcrsAddressType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TcrsAddressType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OECD301"/&gt;
 *     &lt;enumeration value="OECD302"/&gt;
 *     &lt;enumeration value="OECD303"/&gt;
 *     &lt;enumeration value="OECD304"/&gt;
 *     &lt;enumeration value="OECD305"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TcrsAddressType")
@XmlEnum
public enum TcrsAddressType {


    /**
     * Домашня або фактична
     * 
     */
    @XmlEnumValue("OECD301")
    OECD_301("OECD301"),

    /**
     * Домашня
     * 
     */
    @XmlEnumValue("OECD302")
    OECD_302("OECD302"),

    /**
     * Фактична
     * 
     */
    @XmlEnumValue("OECD303")
    OECD_303("OECD303"),

    /**
     * Юридична
     * 
     */
    @XmlEnumValue("OECD304")
    OECD_304("OECD304"),

    /**
     * Невизначена
     * 
     */
    @XmlEnumValue("OECD305")
    OECD_305("OECD305");
    private final String value;

    TcrsAddressType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TcrsAddressType fromValue(String v) {
        for (TcrsAddressType c: TcrsAddressType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
