//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TcrsTIN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TcrsTIN"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="TIN" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;urn:dmt:custodian2016&gt;TIDCode"&gt;
 *                 &lt;attribute name="TINtype" type="{urn:dmt:custodian2016}TcrsTINtype" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Country" type="{urn:dmt:custodian2016}TCountry"/&gt;
 *         &lt;element name="ReasoneEmpty" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ReasoneEmpty"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                         &lt;pattern value="1"/&gt;
 *                         &lt;pattern value="2"/&gt;
 *                         &lt;pattern value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ReasoneEmptyComment" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="300"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dateStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateStop" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TcrsTIN", propOrder = {
    "id",
    "tin",
    "country",
    "reasoneEmpty",
    "dateStart",
    "dateStop"
})
@XmlSeeAlso({
    dmt.custodian2016.TcrsAccount.TINs.TIN.class
})
public class TcrsTIN {

    protected BigInteger id;
    @XmlElement(name = "TIN")
    protected TcrsTIN.TIN tin;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "ReasoneEmpty")
    protected TcrsTIN.ReasoneEmpty reasoneEmpty;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateStart;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateStop;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link TcrsTIN.TIN }
     *     
     */
    public TcrsTIN.TIN getTIN() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcrsTIN.TIN }
     *     
     */
    public void setTIN(TcrsTIN.TIN value) {
        this.tin = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the reasoneEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link TcrsTIN.ReasoneEmpty }
     *     
     */
    public TcrsTIN.ReasoneEmpty getReasoneEmpty() {
        return reasoneEmpty;
    }

    /**
     * Sets the value of the reasoneEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcrsTIN.ReasoneEmpty }
     *     
     */
    public void setReasoneEmpty(TcrsTIN.ReasoneEmpty value) {
        this.reasoneEmpty = value;
    }

    /**
     * Gets the value of the dateStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStart() {
        return dateStart;
    }

    /**
     * Sets the value of the dateStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStart(XMLGregorianCalendar value) {
        this.dateStart = value;
    }

    /**
     * Gets the value of the dateStop property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStop() {
        return dateStop;
    }

    /**
     * Sets the value of the dateStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStop(XMLGregorianCalendar value) {
        this.dateStop = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ReasoneEmpty"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *               &lt;pattern value="1"/&gt;
     *               &lt;pattern value="2"/&gt;
     *               &lt;pattern value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ReasoneEmptyComment" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="300"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reasoneEmpty",
        "reasoneEmptyComment"
    })
    public static class ReasoneEmpty {

        @XmlElement(name = "ReasoneEmpty", required = true)
        protected BigInteger reasoneEmpty;
        @XmlElement(name = "ReasoneEmptyComment")
        protected String reasoneEmptyComment;

        /**
         * Gets the value of the reasoneEmpty property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getReasoneEmpty() {
            return reasoneEmpty;
        }

        /**
         * Sets the value of the reasoneEmpty property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setReasoneEmpty(BigInteger value) {
            this.reasoneEmpty = value;
        }

        /**
         * Gets the value of the reasoneEmptyComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReasoneEmptyComment() {
            return reasoneEmptyComment;
        }

        /**
         * Sets the value of the reasoneEmptyComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReasoneEmptyComment(String value) {
            this.reasoneEmptyComment = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;urn:dmt:custodian2016&gt;TIDCode"&gt;
     *       &lt;attribute name="TINtype" type="{urn:dmt:custodian2016}TcrsTINtype" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TIN {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "TINtype")
        protected String tiNtype;

        /**
         * ИНН физического лица или ЕГРПОУ юридического лица
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the tiNtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTINtype() {
            return tiNtype;
        }

        /**
         * Sets the value of the tiNtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTINtype(String value) {
            this.tiNtype = value;
        }

    }

}
