//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TcrsAcctHolderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TcrsAcctHolderType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CRS101"/&gt;
 *     &lt;enumeration value="CRS102"/&gt;
 *     &lt;enumeration value="CRS103"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TcrsAcctHolderType")
@XmlEnum
public enum TcrsAcctHolderType {


    /**
     * Пасивна НФО з однією або декількома Контролюючими Особами, які є Підзвітними Особами
     * 
     */
    @XmlEnumValue("CRS101")
    CRS_101("CRS101"),

    /**
     * Підзвітна Особа для цілей CRS
     * 
     */
    @XmlEnumValue("CRS102")
    CRS_102("CRS102"),

    /**
     * Пасивна НФО, яка є Підзвітною Особою для цілей CRS
     * 
     */
    @XmlEnumValue("CRS103")
    CRS_103("CRS103");
    private final String value;

    TcrsAcctHolderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TcrsAcctHolderType fromValue(String v) {
        for (TcrsAcctHolderType c: TcrsAcctHolderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
