//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.29 at 08:46:05 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TExchangeСommand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TExchangeСommand"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="stop"/&gt;
 *     &lt;enumeration value="start"/&gt;
 *     &lt;enumeration value="stopTransaction"/&gt;
 *     &lt;enumeration value="startTransaction"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TExchange\u0421ommand")
@XmlEnum
public enum TExchangeСommand {


    /**
     * Команда на повну зипинку обміну
     * 
     */
    @XmlEnumValue("stop")
    STOP("stop"),

    /**
     * Команда на відновлення обміну зупиненого командою stop
     * 
     */
    @XmlEnumValue("start")
    START("start"),

    /**
     * Команда зупинки обміну повідомленнями тупу Transaction
     * 
     */
    @XmlEnumValue("stopTransaction")
    STOP_TRANSACTION("stopTransaction"),

    /**
     * Команда на відновлення обміну зупиненого командою stopTransaction
     * 
     */
    @XmlEnumValue("startTransaction")
    START_TRANSACTION("startTransaction");
    private final String value;

    TExchangeСommand(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TExchangeСommand fromValue(String v) {
        for (TExchangeСommand c: TExchangeСommand.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
