//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.29 at 08:46:05 PM MSK 
//


package dmt.custodian2016;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tfair_value_nbu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tfair_value_nbu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="calcDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="FairValue" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="YTM" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="CleanRate" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tfair_value_nbu", propOrder = {
    "calcDate",
    "fairValue",
    "ytm",
    "cleanRate"
})
public class TfairValueNbu {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar calcDate;
    @XmlElement(name = "FairValue")
    protected float fairValue;
    @XmlElement(name = "YTM")
    protected float ytm;
    @XmlElement(name = "CleanRate")
    protected float cleanRate;

    /**
     * Gets the value of the calcDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCalcDate() {
        return calcDate;
    }

    /**
     * Sets the value of the calcDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCalcDate(XMLGregorianCalendar value) {
        this.calcDate = value;
    }

    /**
     * Gets the value of the fairValue property.
     * 
     */
    public float getFairValue() {
        return fairValue;
    }

    /**
     * Sets the value of the fairValue property.
     * 
     */
    public void setFairValue(float value) {
        this.fairValue = value;
    }

    /**
     * Gets the value of the ytm property.
     * 
     */
    public float getYTM() {
        return ytm;
    }

    /**
     * Sets the value of the ytm property.
     * 
     */
    public void setYTM(float value) {
        this.ytm = value;
    }

    /**
     * Gets the value of the cleanRate property.
     * 
     */
    public float getCleanRate() {
        return cleanRate;
    }

    /**
     * Sets the value of the cleanRate property.
     * 
     */
    public void setCleanRate(float value) {
        this.cleanRate = value;
    }

}
