//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Поиск счетов фактур
 * 
 * <p>Java class for TInvoiceSearch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInvoiceSearch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceNumberYear" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceDate_begin" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceDate_end" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CustomerName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="512"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerIDCode" type="{urn:dmt:custodian2016}TIDCode" minOccurs="0"/&gt;
 *         &lt;element name="AccountNumber" type="{urn:dmt:custodian2016}TAccount_Num" minOccurs="0"/&gt;
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="sendedToABS" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Payments" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Unpaid"/&gt;
 *               &lt;enumeration value="PartiallyPaid"/&gt;
 *               &lt;enumeration value="FullyUnPaid"/&gt;
 *               &lt;enumeration value="FullyPaid"/&gt;
 *               &lt;enumeration value="All"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="line_Date_begin" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="line_Date_end" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="onlyClose" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="includePrePaid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInvoiceSearch", propOrder = {
    "invoiceNumber",
    "invoiceNumberYear",
    "invoiceDateBegin",
    "invoiceDateEnd",
    "customerName",
    "customerIDCode",
    "accountNumber",
    "customerID",
    "sendedToABS",
    "payments",
    "lineDateBegin",
    "lineDateEnd",
    "onlyClose",
    "includePrePaid"
})
public class TInvoiceSearch {

    @XmlElement(name = "InvoiceNumber")
    protected BigInteger invoiceNumber;
    @XmlElement(name = "InvoiceNumberYear")
    protected BigInteger invoiceNumberYear;
    @XmlElement(name = "InvoiceDate_begin")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDateBegin;
    @XmlElement(name = "InvoiceDate_end")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDateEnd;
    @XmlElement(name = "CustomerName")
    protected String customerName;
    @XmlElement(name = "CustomerIDCode")
    protected String customerIDCode;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "CustomerID")
    protected BigInteger customerID;
    protected Boolean sendedToABS;
    @XmlElement(name = "Payments")
    protected String payments;
    @XmlElement(name = "line_Date_begin")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lineDateBegin;
    @XmlElement(name = "line_Date_end")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lineDateEnd;
    protected Boolean onlyClose;
    protected Boolean includePrePaid;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvoiceNumber(BigInteger value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceNumberYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvoiceNumberYear() {
        return invoiceNumberYear;
    }

    /**
     * Sets the value of the invoiceNumberYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvoiceNumberYear(BigInteger value) {
        this.invoiceNumberYear = value;
    }

    /**
     * Gets the value of the invoiceDateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDateBegin() {
        return invoiceDateBegin;
    }

    /**
     * Sets the value of the invoiceDateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDateBegin(XMLGregorianCalendar value) {
        this.invoiceDateBegin = value;
    }

    /**
     * Gets the value of the invoiceDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDateEnd() {
        return invoiceDateEnd;
    }

    /**
     * Sets the value of the invoiceDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDateEnd(XMLGregorianCalendar value) {
        this.invoiceDateEnd = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerIDCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerIDCode() {
        return customerIDCode;
    }

    /**
     * Sets the value of the customerIDCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerIDCode(String value) {
        this.customerIDCode = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerID(BigInteger value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the sendedToABS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendedToABS() {
        return sendedToABS;
    }

    /**
     * Sets the value of the sendedToABS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendedToABS(Boolean value) {
        this.sendedToABS = value;
    }

    /**
     * Gets the value of the payments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayments() {
        return payments;
    }

    /**
     * Sets the value of the payments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayments(String value) {
        this.payments = value;
    }

    /**
     * Gets the value of the lineDateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLineDateBegin() {
        return lineDateBegin;
    }

    /**
     * Sets the value of the lineDateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLineDateBegin(XMLGregorianCalendar value) {
        this.lineDateBegin = value;
    }

    /**
     * Gets the value of the lineDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLineDateEnd() {
        return lineDateEnd;
    }

    /**
     * Sets the value of the lineDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLineDateEnd(XMLGregorianCalendar value) {
        this.lineDateEnd = value;
    }

    /**
     * Gets the value of the onlyClose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnlyClose() {
        return onlyClose;
    }

    /**
     * Sets the value of the onlyClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnlyClose(Boolean value) {
        this.onlyClose = value;
    }

    /**
     * Gets the value of the includePrePaid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludePrePaid() {
        return includePrePaid;
    }

    /**
     * Sets the value of the includePrePaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludePrePaid(Boolean value) {
        this.includePrePaid = value;
    }

}
