//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.29 at 08:46:05 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Нотіфікація в наслідок виконання операції що призводить до руху на рахунку. Нотифікація містить поточний стан рахунку посточальника/отримувача
 * 
 * <p>Java class for TNotificationTransactionBalance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TNotificationTransactionBalance"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TNotification"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Balance"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Source" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *                             &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
 *                             &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Destination" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *                             &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
 *                             &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNotificationTransactionBalance", propOrder = {
    "balance"
})
public class TNotificationTransactionBalance
    extends TNotification
{

    @XmlElement(name = "Balance", required = true)
    protected TNotificationTransactionBalance.Balance balance;

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link TNotificationTransactionBalance.Balance }
     *     
     */
    public TNotificationTransactionBalance.Balance getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNotificationTransactionBalance.Balance }
     *     
     */
    public void setBalance(TNotificationTransactionBalance.Balance value) {
        this.balance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Source" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
     *                   &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
     *                   &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Destination" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
     *                   &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
     *                   &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source",
        "destination"
    })
    public static class Balance {

        @XmlElement(name = "Source")
        protected TNotificationTransactionBalance.Balance.Source source;
        @XmlElement(name = "Destination")
        protected TNotificationTransactionBalance.Balance.Destination destination;

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link TNotificationTransactionBalance.Balance.Source }
         *     
         */
        public TNotificationTransactionBalance.Balance.Source getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link TNotificationTransactionBalance.Balance.Source }
         *     
         */
        public void setSource(TNotificationTransactionBalance.Balance.Source value) {
            this.source = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link TNotificationTransactionBalance.Balance.Destination }
         *     
         */
        public TNotificationTransactionBalance.Balance.Destination getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link TNotificationTransactionBalance.Balance.Destination }
         *     
         */
        public void setDestination(TNotificationTransactionBalance.Balance.Destination value) {
            this.destination = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
         *         &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
         *         &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "account",
            "isin",
            "rows"
        })
        public static class Destination {

            @XmlElement(name = "Account", required = true)
            protected String account;
            @XmlElement(name = "ISIN")
            protected TISIN isin;
            @XmlElement(name = "Rows")
            protected TStatementOfHoldingRowsAbstact rows;

            /**
             * Gets the value of the account property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccount() {
                return account;
            }

            /**
             * Sets the value of the account property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccount(String value) {
                this.account = value;
            }

            /**
             * Gets the value of the isin property.
             * 
             * @return
             *     possible object is
             *     {@link TISIN }
             *     
             */
            public TISIN getISIN() {
                return isin;
            }

            /**
             * Sets the value of the isin property.
             * 
             * @param value
             *     allowed object is
             *     {@link TISIN }
             *     
             */
            public void setISIN(TISIN value) {
                this.isin = value;
            }

            /**
             * Gets the value of the rows property.
             * 
             * @return
             *     possible object is
             *     {@link TStatementOfHoldingRowsAbstact }
             *     
             */
            public TStatementOfHoldingRowsAbstact getRows() {
                return rows;
            }

            /**
             * Sets the value of the rows property.
             * 
             * @param value
             *     allowed object is
             *     {@link TStatementOfHoldingRowsAbstact }
             *     
             */
            public void setRows(TStatementOfHoldingRowsAbstact value) {
                this.rows = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
         *         &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN" minOccurs="0"/&gt;
         *         &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "account",
            "isin",
            "rows"
        })
        public static class Source {

            @XmlElement(name = "Account", required = true)
            protected String account;
            @XmlElement(name = "ISIN")
            protected TISIN isin;
            @XmlElement(name = "Rows")
            protected TStatementOfHoldingRowsAbstact rows;

            /**
             * Gets the value of the account property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccount() {
                return account;
            }

            /**
             * Sets the value of the account property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccount(String value) {
                this.account = value;
            }

            /**
             * Gets the value of the isin property.
             * 
             * @return
             *     possible object is
             *     {@link TISIN }
             *     
             */
            public TISIN getISIN() {
                return isin;
            }

            /**
             * Sets the value of the isin property.
             * 
             * @param value
             *     allowed object is
             *     {@link TISIN }
             *     
             */
            public void setISIN(TISIN value) {
                this.isin = value;
            }

            /**
             * Gets the value of the rows property.
             * 
             * @return
             *     possible object is
             *     {@link TStatementOfHoldingRowsAbstact }
             *     
             */
            public TStatementOfHoldingRowsAbstact getRows() {
                return rows;
            }

            /**
             * Sets the value of the rows property.
             * 
             * @param value
             *     allowed object is
             *     {@link TStatementOfHoldingRowsAbstact }
             *     
             */
            public void setRows(TStatementOfHoldingRowsAbstact value) {
                this.rows = value;
            }

        }

    }

}
