//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.29 at 08:46:05 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Нотіфікація в наслідок виконання операції що призводить до руху на рахунк
 * 
 * 
 * <p>Java class for TNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TNotification_parent"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NotificationType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{urn:dmt:custodian2016}TNotificationType"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNotification", propOrder = {
    "notificationType"
})
@XmlSeeAlso({
    TNotificationTransaction2 .class,
    TNotificationTransaction3 .class,
    TNotificationTransactionBalance.class,
    TNotificationTransaction.class,
    TNotificationAccount.class,
    TNotificationAccountAbstract.class,
    TNotificationAccountBlock.class,
    TNotificationAccountBlockOne.class,
    TNotificationConnectionStatus.class,
    TNotificationExchangeAction.class
})
public class TNotification
    extends TNotificationParent
{

    @XmlElement(name = "NotificationType", required = true)
    protected TNotificationType notificationType;

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link TNotificationType }
     *     
     */
    public TNotificationType getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNotificationType }
     *     
     */
    public void setNotificationType(TNotificationType value) {
        this.notificationType = value;
    }

}
