//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.29 at 08:46:05 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Нотіфікація в наслідок виконання операції що призводить до руху на рахунку с розділення по балансовиї рахунка, та інформацією про номер та дата угоди
 * 
 * <p>Java class for TNotificationTransaction3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TNotificationTransaction3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TNotification"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="OrderIDs" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OrderID_Source" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="OrderID_Destination" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ISIN" type="{urn:dmt:custodian2016}TISIN"/&gt;
 *         &lt;element name="AccountSource" type="{urn:dmt:custodian2016}TAccount_Num" minOccurs="0"/&gt;
 *         &lt;element name="BalAccountSource" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{urn:dmt:custodian2016}TBalAcc"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AgregateAccountIDSource" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
 *         &lt;element name="AccountDestination" type="{urn:dmt:custodian2016}TAccount_Num" minOccurs="0"/&gt;
 *         &lt;element name="BalAccountDestination" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{urn:dmt:custodian2016}TBalAcc"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AgregateAccountIDDestination" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="orderTypeCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="26"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Agreement" type="{urn:dmt:custodian2016}TAgreementBase" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNotificationTransaction3", propOrder = {
    "operID",
    "orderID",
    "orderIDs",
    "date",
    "isin",
    "accountSource",
    "balAccountSource",
    "agregateAccountIDSource",
    "accountDestination",
    "balAccountDestination",
    "agregateAccountIDDestination",
    "quantity",
    "orderTypeCode",
    "agreement"
})
public class TNotificationTransaction3
    extends TNotification
{

    @XmlElement(name = "OperID", required = true)
    protected BigInteger operID;
    @XmlElement(name = "OrderID", required = true)
    protected BigInteger orderID;
    @XmlElement(name = "OrderIDs")
    protected TNotificationTransaction3 .OrderIDs orderIDs;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "ISIN", required = true)
    protected TISIN isin;
    @XmlElement(name = "AccountSource")
    protected String accountSource;
    @XmlElement(name = "BalAccountSource")
    protected TNotificationTransaction3 .BalAccountSource balAccountSource;
    @XmlElement(name = "AgregateAccountIDSource")
    protected String agregateAccountIDSource;
    @XmlElement(name = "AccountDestination")
    protected String accountDestination;
    @XmlElement(name = "BalAccountDestination")
    protected TNotificationTransaction3 .BalAccountDestination balAccountDestination;
    @XmlElement(name = "AgregateAccountIDDestination")
    protected String agregateAccountIDDestination;
    @XmlElement(name = "Quantity")
    protected long quantity;
    protected String orderTypeCode;
    @XmlElement(name = "Agreement")
    protected TAgreementBase agreement;

    /**
     * Gets the value of the operID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOperID() {
        return operID;
    }

    /**
     * Sets the value of the operID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOperID(BigInteger value) {
        this.operID = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderID(BigInteger value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the orderIDs property.
     * 
     * @return
     *     possible object is
     *     {@link TNotificationTransaction3 .OrderIDs }
     *     
     */
    public TNotificationTransaction3 .OrderIDs getOrderIDs() {
        return orderIDs;
    }

    /**
     * Sets the value of the orderIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNotificationTransaction3 .OrderIDs }
     *     
     */
    public void setOrderIDs(TNotificationTransaction3 .OrderIDs value) {
        this.orderIDs = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link TISIN }
     *     
     */
    public TISIN getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TISIN }
     *     
     */
    public void setISIN(TISIN value) {
        this.isin = value;
    }

    /**
     * Gets the value of the accountSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountSource() {
        return accountSource;
    }

    /**
     * Sets the value of the accountSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountSource(String value) {
        this.accountSource = value;
    }

    /**
     * Gets the value of the balAccountSource property.
     * 
     * @return
     *     possible object is
     *     {@link TNotificationTransaction3 .BalAccountSource }
     *     
     */
    public TNotificationTransaction3 .BalAccountSource getBalAccountSource() {
        return balAccountSource;
    }

    /**
     * Sets the value of the balAccountSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNotificationTransaction3 .BalAccountSource }
     *     
     */
    public void setBalAccountSource(TNotificationTransaction3 .BalAccountSource value) {
        this.balAccountSource = value;
    }

    /**
     * Gets the value of the agregateAccountIDSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgregateAccountIDSource() {
        return agregateAccountIDSource;
    }

    /**
     * Sets the value of the agregateAccountIDSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgregateAccountIDSource(String value) {
        this.agregateAccountIDSource = value;
    }

    /**
     * Gets the value of the accountDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDestination() {
        return accountDestination;
    }

    /**
     * Sets the value of the accountDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDestination(String value) {
        this.accountDestination = value;
    }

    /**
     * Gets the value of the balAccountDestination property.
     * 
     * @return
     *     possible object is
     *     {@link TNotificationTransaction3 .BalAccountDestination }
     *     
     */
    public TNotificationTransaction3 .BalAccountDestination getBalAccountDestination() {
        return balAccountDestination;
    }

    /**
     * Sets the value of the balAccountDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNotificationTransaction3 .BalAccountDestination }
     *     
     */
    public void setBalAccountDestination(TNotificationTransaction3 .BalAccountDestination value) {
        this.balAccountDestination = value;
    }

    /**
     * Gets the value of the agregateAccountIDDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgregateAccountIDDestination() {
        return agregateAccountIDDestination;
    }

    /**
     * Sets the value of the agregateAccountIDDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgregateAccountIDDestination(String value) {
        this.agregateAccountIDDestination = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the orderTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTypeCode() {
        return orderTypeCode;
    }

    /**
     * Sets the value of the orderTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTypeCode(String value) {
        this.orderTypeCode = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * @return
     *     possible object is
     *     {@link TAgreementBase }
     *     
     */
    public TAgreementBase getAgreement() {
        return agreement;
    }

    /**
     * Sets the value of the agreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAgreementBase }
     *     
     */
    public void setAgreement(TAgreementBase value) {
        this.agreement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{urn:dmt:custodian2016}TBalAcc"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BalAccountDestination
        extends TBalAcc
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{urn:dmt:custodian2016}TBalAcc"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BalAccountSource
        extends TBalAcc
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OrderID_Source" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="OrderID_Destination" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderIDSource",
        "orderIDDestination"
    })
    public static class OrderIDs {

        @XmlElement(name = "OrderID_Source")
        protected BigInteger orderIDSource;
        @XmlElement(name = "OrderID_Destination")
        protected BigInteger orderIDDestination;

        /**
         * Gets the value of the orderIDSource property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrderIDSource() {
            return orderIDSource;
        }

        /**
         * Sets the value of the orderIDSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrderIDSource(BigInteger value) {
            this.orderIDSource = value;
        }

        /**
         * Gets the value of the orderIDDestination property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrderIDDestination() {
            return orderIDDestination;
        }

        /**
         * Sets the value of the orderIDDestination property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrderIDDestination(BigInteger value) {
            this.orderIDDestination = value;
        }

    }

}
