//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Участник сделки
 * 
 * <p>Java class for TParticipant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TParticipant"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MDO" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *         &lt;element name="Name" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="150"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IDCode" type="{urn:dmt:custodian2016}TIDCode" minOccurs="0"/&gt;
 *         &lt;element name="Doc" type="{urn:dmt:custodian2016}Tdoc" minOccurs="0"/&gt;
 *         &lt;element name="Level" type="{urn:dmt:custodian2016}TAccountLevel" minOccurs="0"/&gt;
 *         &lt;element name="AccountType" type="{urn:dmt:custodian2016}TnbuAccountType" minOccurs="0"/&gt;
 *         &lt;element name="Broker" type="{urn:dmt:custodian2016}TBroker" minOccurs="0"/&gt;
 *         &lt;element name="AgregateAccountID" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
 *         &lt;element name="bankDetail" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="MFO"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;length value="6"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="IBAN"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;length value="34"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ParticipantCode" type="{urn:dmt:custodian2016}TIDCode" minOccurs="0"/&gt;
 *                   &lt;element name="finalBeneficiary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TParticipant", propOrder = {
    "mdo",
    "account",
    "name",
    "idCode",
    "doc",
    "level",
    "accountType",
    "broker",
    "agregateAccountID",
    "bankDetail"
})
public class TParticipant {

    @XmlElement(name = "MDO")
    protected String mdo;
    @XmlElement(name = "Account", required = true)
    protected String account;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "IDCode")
    protected String idCode;
    @XmlElement(name = "Doc")
    protected Tdoc doc;
    @XmlElement(name = "Level")
    protected BigInteger level;
    @XmlElement(name = "AccountType")
    protected BigInteger accountType;
    @XmlElement(name = "Broker")
    protected TBroker broker;
    @XmlElement(name = "AgregateAccountID")
    protected String agregateAccountID;
    protected TParticipant.BankDetail bankDetail;

    /**
     * Gets the value of the mdo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMDO() {
        return mdo;
    }

    /**
     * Sets the value of the mdo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMDO(String value) {
        this.mdo = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccount(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the idCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCode() {
        return idCode;
    }

    /**
     * Sets the value of the idCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCode(String value) {
        this.idCode = value;
    }

    /**
     * Gets the value of the doc property.
     * 
     * @return
     *     possible object is
     *     {@link Tdoc }
     *     
     */
    public Tdoc getDoc() {
        return doc;
    }

    /**
     * Sets the value of the doc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tdoc }
     *     
     */
    public void setDoc(Tdoc value) {
        this.doc = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLevel(BigInteger value) {
        this.level = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountType(BigInteger value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the broker property.
     * 
     * @return
     *     possible object is
     *     {@link TBroker }
     *     
     */
    public TBroker getBroker() {
        return broker;
    }

    /**
     * Sets the value of the broker property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBroker }
     *     
     */
    public void setBroker(TBroker value) {
        this.broker = value;
    }

    /**
     * Gets the value of the agregateAccountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgregateAccountID() {
        return agregateAccountID;
    }

    /**
     * Sets the value of the agregateAccountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgregateAccountID(String value) {
        this.agregateAccountID = value;
    }

    /**
     * Gets the value of the bankDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TParticipant.BankDetail }
     *     
     */
    public TParticipant.BankDetail getBankDetail() {
        return bankDetail;
    }

    /**
     * Sets the value of the bankDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TParticipant.BankDetail }
     *     
     */
    public void setBankDetail(TParticipant.BankDetail value) {
        this.bankDetail = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="MFO"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;length value="6"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="IBAN"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;length value="34"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ParticipantCode" type="{urn:dmt:custodian2016}TIDCode" minOccurs="0"/&gt;
     *         &lt;element name="finalBeneficiary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mfo",
        "iban",
        "participantCode",
        "finalBeneficiary"
    })
    public static class BankDetail {

        @XmlElement(name = "MFO", required = true)
        protected String mfo;
        @XmlElement(name = "IBAN", required = true)
        protected String iban;
        @XmlElement(name = "ParticipantCode")
        protected String participantCode;
        protected String finalBeneficiary;

        /**
         * Gets the value of the mfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMFO() {
            return mfo;
        }

        /**
         * Sets the value of the mfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMFO(String value) {
            this.mfo = value;
        }

        /**
         * Gets the value of the iban property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIBAN() {
            return iban;
        }

        /**
         * Sets the value of the iban property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIBAN(String value) {
            this.iban = value;
        }

        /**
         * Gets the value of the participantCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParticipantCode() {
            return participantCode;
        }

        /**
         * Sets the value of the participantCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParticipantCode(String value) {
            this.participantCode = value;
        }

        /**
         * Gets the value of the finalBeneficiary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFinalBeneficiary() {
            return finalBeneficiary;
        }

        /**
         * Sets the value of the finalBeneficiary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFinalBeneficiary(String value) {
            this.finalBeneficiary = value;
        }

    }

}
