//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * Запит на перевірку по санкційним спискам
 * 
 * <p>Java class for TSanctionCheckRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSanctionCheckRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shortName" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;urn:dmt:custodian2016&gt;TShortName"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longName" type="{urn:dmt:custodian2016}TLongName" minOccurs="0"/&gt;
 *         &lt;element name="shortName_International" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;urn:dmt:custodian2016&gt;TShortName"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longName_International" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;urn:dmt:custodian2016&gt;TLongName"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="code" type="{urn:dmt:custodian2016}TIDCode" minOccurs="0"/&gt;
 *         &lt;element name="docSerial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="docNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="26"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="typeCustomer"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{urn:dmt:custodian2016}TClientType"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Similarity" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSanctionCheckRequest", propOrder = {
    "shortName",
    "longName",
    "shortNameInternational",
    "longNameInternational",
    "code",
    "docSerial",
    "docNumber",
    "typeCustomer",
    "similarity"
})
public class TSanctionCheckRequest {

    protected TSanctionCheckRequest.ShortName shortName;
    protected String longName;
    @XmlElement(name = "shortName_International")
    protected TSanctionCheckRequest.ShortNameInternational shortNameInternational;
    @XmlElement(name = "longName_International")
    protected TSanctionCheckRequest.LongNameInternational longNameInternational;
    protected String code;
    protected String docSerial;
    protected String docNumber;
    @XmlElement(required = true)
    protected String typeCustomer;
    @XmlElement(name = "Similarity")
    protected BigInteger similarity;

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link TSanctionCheckRequest.ShortName }
     *     
     */
    public TSanctionCheckRequest.ShortName getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSanctionCheckRequest.ShortName }
     *     
     */
    public void setShortName(TSanctionCheckRequest.ShortName value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongName(String value) {
        this.longName = value;
    }

    /**
     * Gets the value of the shortNameInternational property.
     * 
     * @return
     *     possible object is
     *     {@link TSanctionCheckRequest.ShortNameInternational }
     *     
     */
    public TSanctionCheckRequest.ShortNameInternational getShortNameInternational() {
        return shortNameInternational;
    }

    /**
     * Sets the value of the shortNameInternational property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSanctionCheckRequest.ShortNameInternational }
     *     
     */
    public void setShortNameInternational(TSanctionCheckRequest.ShortNameInternational value) {
        this.shortNameInternational = value;
    }

    /**
     * Gets the value of the longNameInternational property.
     * 
     * @return
     *     possible object is
     *     {@link TSanctionCheckRequest.LongNameInternational }
     *     
     */
    public TSanctionCheckRequest.LongNameInternational getLongNameInternational() {
        return longNameInternational;
    }

    /**
     * Sets the value of the longNameInternational property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSanctionCheckRequest.LongNameInternational }
     *     
     */
    public void setLongNameInternational(TSanctionCheckRequest.LongNameInternational value) {
        this.longNameInternational = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the docSerial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocSerial() {
        return docSerial;
    }

    /**
     * Sets the value of the docSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocSerial(String value) {
        this.docSerial = value;
    }

    /**
     * Gets the value of the docNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the typeCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCustomer() {
        return typeCustomer;
    }

    /**
     * Sets the value of the typeCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCustomer(String value) {
        this.typeCustomer = value;
    }

    /**
     * Gets the value of the similarity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSimilarity() {
        return similarity;
    }

    /**
     * Sets the value of the similarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSimilarity(BigInteger value) {
        this.similarity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;urn:dmt:custodian2016&gt;TLongName"&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class LongNameInternational {

        @XmlValue
        protected String value;

        /**
         * Полное наименоване для юридических лиц/ПИБ для физических
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;urn:dmt:custodian2016&gt;TShortName"&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ShortName {

        @XmlValue
        protected String value;

        /**
         * Сокращеное наименоване для юридических лиц/ПИБ для физических
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;urn:dmt:custodian2016&gt;TShortName"&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ShortNameInternational {

        @XmlValue
        protected String value;

        /**
         * Сокращеное наименоване для юридических лиц/ПИБ для физических
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
