//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.30 at 03:15:09 PM MSK 
//


package dmt.custodian2016;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Содержимое выписки про состояние счета(с расширенным блоком иформации о ИСИН)
 * 
 * <p>Java class for TStatement_of_Holding_rowsV3_simple complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStatement_of_Holding_rowsV3_simple"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TStatement_of_Holding_rows_abstact"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="Row" type="{urn:dmt:custodian2016}TStatement_of_Holding_rowV3_simple"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatement_of_Holding_rowsV3_simple", propOrder = {
    "row"
})
public class TStatementOfHoldingRowsV3Simple
    extends TStatementOfHoldingRowsAbstact
{

    @XmlElement(name = "Row")
    protected List<TStatementOfHoldingRowV3Simple> row;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TStatementOfHoldingRowV3Simple }
     * 
     * 
     */
    public List<TStatementOfHoldingRowV3Simple> getRow() {
        if (row == null) {
            row = new ArrayList<TStatementOfHoldingRowV3Simple>();
        }
        return this.row;
    }

}
