//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Запрос на выписку по операциям
 * 
 * <p>Java class for TStatement_of_Transactions_Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStatement_of_Transactions_Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TStatementRequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dateStart" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="dateStop" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="eMailResponce" type="{urn:dmt:custodian2016}TeMailResponce" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatement_of_Transactions_Request", propOrder = {
    "dateStart",
    "dateStop",
    "eMailResponce"
})
public class TStatementOfTransactionsRequest
    extends TStatementRequestBase
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateStop;
    protected TeMailResponce eMailResponce;

    /**
     * Gets the value of the dateStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStart() {
        return dateStart;
    }

    /**
     * Sets the value of the dateStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStart(XMLGregorianCalendar value) {
        this.dateStart = value;
    }

    /**
     * Gets the value of the dateStop property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStop() {
        return dateStop;
    }

    /**
     * Sets the value of the dateStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStop(XMLGregorianCalendar value) {
        this.dateStop = value;
    }

    /**
     * Gets the value of the eMailResponce property.
     * 
     * @return
     *     possible object is
     *     {@link TeMailResponce }
     *     
     */
    public TeMailResponce getEMailResponce() {
        return eMailResponce;
    }

    /**
     * Sets the value of the eMailResponce property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeMailResponce }
     *     
     */
    public void setEMailResponce(TeMailResponce value) {
        this.eMailResponce = value;
    }

}
