//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Налог удержаный с дохода
 * 
 * <p>Java class for TTax complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTax"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaxType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Other"/&gt;
 *               &lt;enumeration value="Tax.Income"/&gt;
 *               &lt;enumeration value="Tax.Military"/&gt;
 *               &lt;enumeration value="Tax.Repatriation"/&gt;
 *               &lt;enumeration value="Tax.Other"/&gt;
 *               &lt;enumeration value="DVS"/&gt;
 *               &lt;enumeration value="Commission"/&gt;
 *               &lt;enumeration value="CommissionPrev"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TaxPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="TaxValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TaxBankDetail" type="{urn:dmt:custodian2016}TMoneyBankDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTax", propOrder = {
    "taxType",
    "taxPercent",
    "taxValue",
    "taxBankDetail"
})
public class TTax {

    @XmlElement(name = "TaxType", required = true)
    protected String taxType;
    @XmlElement(name = "TaxPercent")
    protected BigDecimal taxPercent;
    @XmlElement(name = "TaxValue", required = true)
    protected BigDecimal taxValue;
    @XmlElement(name = "TaxBankDetail")
    protected TMoneyBankDetail taxBankDetail;

    /**
     * Gets the value of the taxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxType(String value) {
        this.taxType = value;
    }

    /**
     * Gets the value of the taxPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPercent() {
        return taxPercent;
    }

    /**
     * Sets the value of the taxPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPercent(BigDecimal value) {
        this.taxPercent = value;
    }

    /**
     * Gets the value of the taxValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxValue() {
        return taxValue;
    }

    /**
     * Sets the value of the taxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxValue(BigDecimal value) {
        this.taxValue = value;
    }

    /**
     * Gets the value of the taxBankDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TMoneyBankDetail }
     *     
     */
    public TMoneyBankDetail getTaxBankDetail() {
        return taxBankDetail;
    }

    /**
     * Sets the value of the taxBankDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMoneyBankDetail }
     *     
     */
    public void setTaxBankDetail(TMoneyBankDetail value) {
        this.taxBankDetail = value;
    }

}
