//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.09 at 06:17:34 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TTransactionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FOP"/&gt;
 *     &lt;enumeration value="DVP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TTransactionType")
@XmlEnum
public enum TTransactionType {


    /**
     * Тип транзакції free of payment (Поставка без оплати)
     * 
     */
    FOP,

    /**
     * Тип транзакції: Delivery Versus Payment (Поставка проти оплати)
     * 
     */
    DVP;

    public String value() {
        return name();
    }

    public static TTransactionType fromValue(String v) {
        return valueOf(v);
    }

}
